version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
      - echo no commands executed before building commands...
  build:
    commands:
      - mvn install
      - echo npm install completed on `date`
      - echo install completed on `date`
  post_build:
    commands:
      - echo build completed on `date`
      - mv ./target/shop-api-0.0.1-SNAPSHOT.jar ./target/app.jar
      - chmod 777 ./appstart.sh
artifacts:
  files:
    - target/app.jar
    - batch/*
    - appstart.sh
    - appspec.yml
